Adding DynamicFC function
MabbottLab/MEGneto pull request #162
Opened 2024-08-14 17:29 UTC by biancah-1

2024-08-14 19:56 UTC, j-tseng requested changes
* stop leaving newlines before `end`s! 
* decouple the figure generation from the actual function itself
* make the figure generation separate function something that can loop across participants

2024-08-14 19:56 UTC, j-tseng commented on Step4c_DynamicFC.m
> +% Inputs:
"Inputs" in this section of the function header is usually reserved for actual input args into the `Step4c_DynamicFC` function. You should clarify that these parameters are specified in the config and highlight the appropriate config field (just like the FieldTrip functions usually do)

2024-08-14 19:56 UTC, j-tseng commented on Step4c_DynamicFC.m
> +%       .mat containing connectivity matrices (window number x ROI x ROI x
Returns is reserved for function returns, and there are none here. Instead, describe the file naming convention for what's saved to file and make the heading something different.

2024-08-14 19:56 UTC, j-tseng commented on Step4c_DynamicFC.m
> +%       window, truncates at last multiple
The last bit about truncation is confusing to layperson so rephrase to be more lay-friendly, possibly with example

2024-08-14 19:56 UTC, j-tseng commented on Step4c_DynamicFC.m
> +    winsize  = config.step4c.winsize;
If you're going to indent-align the `=`, then make sure they're aligned! And also, comment what these variables are - keep in mind that the audience reviewing your code is not always technical

2024-08-14 19:56 UTC, j-tseng commented on Step4c_DynamicFC.m
> +
Why is there an empty line here?

2024-08-14 19:56 UTC, j-tseng commented on Step4c_DynamicFC.m
> +        % variables that get reused
Not sure what this comment means - elaborate / be clear

2024-08-14 19:56 UTC, j-tseng commented on Step4c_DynamicFC.m
> +            warning(sprintf('Chosen window size captures less than one cycle of frequency band %d - %d Hz',f_low,f_high))
Should this be a warning or an error?

2024-08-14 19:56 UTC, j-tseng commented on Step4c_DynamicFC.m
> +            cfg.latency       = [t t+ winsize];
Remove the space between `+` and `winsize`, or else it looks confusing (as if they are separate elements of the array)

2024-08-14 19:56 UTC, j-tseng commented on Step4c_DynamicFC.m
> +    save([this_output '/step4c_connDFC.mat'], 'connDFC');
Save right after the results are generated to avoid any issues posed by figure generation

2024-08-14 19:56 UTC, j-tseng commented on Step4c_DynamicFC.m
> +        % SAVING ROI X ROI MATRICES OVER TIME AS FIGURE FOR CURRENT
Let's decouple the figure generation from the actual function - make a separate visualization function for this

2024-08-14 19:56 UTC, j-tseng commented on Step4c_DynamicFC.m
> +        labels = this_conn.label;
Decoupling this will solve it but beware of having too many wasted variables that are copies of info already encoded elsewhere

2024-08-14 19:56 UTC, j-tseng commented on Step4c_DynamicFC.m
> +
why the newline / space

2024-08-14 19:56 UTC, j-tseng commented on Step4c_DynamicFC.m
> +        title(tcl,sprintf('Dynamic Functional Connectivity For Frequency %d-%d Hz',f_low,f_high));
If this is participant-specific, then it should be indicated in the title. Also, since ultimately we will never look at figures on an individual participant basis, you should make the decoupled figure generation function something that averages across participants or something.

2024-08-20 18:34 UTC, biancah-1 commented on Step4c_DynamicFC.m
> +            warning(sprintf('Chosen window size captures less than one cycle of frequency band %d - %d Hz',f_low,f_high))
I left it as a warning just b/c the two lower frequency bands will limit the window the most, assuming it was being run across all bands. Though a warning assumes the user is pretty conscientious about what they're doing. But yeah not sure, easy change though.

2024-08-20 18:51 UTC, j-tseng requested changes
The main dFC function looks good but the plotting function does not look nearly as pretty as the rest - fix the alignment/spacing.

2024-08-20 18:51 UTC, j-tseng commented on DynamicFC_plot.m
> +            this_output = sprintf('/home/bha/%s/ses-%.2d',pid,visits(v));
you forgot to swap this back for the generalized path

2024-08-20 18:51 UTC, j-tseng commented on DynamicFC_plot.m
> +        %save('/home/bha/dfc_avg.mat', 'dfc_avg');
remove comment references to home folders

2024-08-23 18:41 UTC, j-tseng approved these changes

2024-08-23 19:10 UTC, merged